name: tfg
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.10.14
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - ale-py==0.8.1
      - autorom==0.6.1
      - autorom-accept-rom-license==0.6.1
      - cachetools==5.3.3
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - fonttools==4.53.0
      - fsspec==2024.2.0
      - google-auth==2.30.0
      - google-auth-oauthlib==1.2.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - idna==3.7
      - importlib-resources==6.4.0
      - jinja2==3.1.3
      - joblib==1.4.2
      - keras==3.3.3
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - pandas==2.2.2
      - pillow==10.2.0
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygame==2.6.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - scikit-learn==1.5.0
      - scipy==1.14.0
      - shimmy==1.3.0
      - six==1.16.0
      - stable-baselines3==2.3.2
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorflow==2.15.0
      - tensorflow-cpu==2.16.1
      - tensorflow-estimator==2.15.0
      - threadpoolctl==3.5.0
      - torch==2.3.1+cpu
      - torchaudio==2.3.1+cpu
      - torchvision==0.18.1+cpu
      - tqdm==4.66.4
      - tzdata==2024.1
      - urllib3==2.2.2
      - wrapt==1.14.1
# prefix: /home/julian/anaconda3/envs/tfg
